// Curated "golden" objects - hand-crafted and tested
// Keys must match normalized prompt output (lowercase, 1-2 words)
// These take priority over Firebase and Gemini-generated code

export const CURATED_OBJECTS = {
  'catapult': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world,G=40,SPD=55,b=w.createBody({type:'dynamic',position:v(x,y)});b.createFixture(p.Box(4,1),{density:5,friction:.5});registerObject({body:b,type:'rect',hw:4,hh:1,color:'#8b4513'});var wf=function(o){var k=w.createBody({type:'dynamic',position:v(x+o,y+1.5)});k.createFixture(p.Circle(1.2),{density:2,friction:.8});registerObject({body:k,type:'circle',radius:1.2,color:'#5d4037'});w.createJoint(new p.RevoluteJoint({enableMotor:true,motorSpeed:-8,maxMotorTorque:500},b,k,k.getPosition()))};wf(2.5);wf(-2.5);var a=w.createBody({type:'dynamic',position:v(x+1,y-1.5),angle:.1});a.createFixture(p.Box(3.5,.3),{density:1});a.createFixture(p.Box(.2,.8,v(3.3,-.6),0),{density:1});registerObject({body:a,type:'rect',hw:3.5,hh:.3,color:'#cd853f'});var j=w.createJoint(new p.RevoluteJoint({enableLimit:true,lowerAngle:-2.5,upperAngle:.2,enableMotor:true,maxMotorTorque:30000,motorSpeed:0},b,a,v(x-2,y-1)));var t=0,rock=null,rockJoint=null,fireStart=0,nextFire=90;function loadRock(){var ap=a.getWorldPoint(v(3.3,-0.8));rock=w.createBody({type:'dynamic',position:ap});rock.createFixture(p.Circle(.7),{density:8,friction:1});registerObject({body:rock,type:'circle',radius:.7,color:'#2c3e50'});rockJoint=w.createJoint(new p.WeldJoint({},a,rock,ap))}loadRock();return{update:function(){t++;var tg=getTarget();if(tg&&!fireStart&&t>=nextFire){j.setMotorSpeed(-40);fireStart=t}if(fireStart&&t-fireStart>15){if(rockJoint){w.destroyJoint(rockJoint);rockJoint=null}if(rock){var av=a.getLinearVelocityFromWorldPoint(a.getWorldPoint(v(3.3,0)));rock.setLinearVelocity(av);rock=null}j.setMotorSpeed(8);fireStart=0;nextFire=t+150;setTimeout(loadRock,1200)}}}`,

  'helicopter': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world;var body=w.createBody({type:'dynamic',position:v(x,y),angularDamping:2,linearDamping:0.5});body.createFixture(p.Box(3,1),{density:1.5});body.createFixture(p.Box(1,0.8,v(0,-1)),{density:1});body.setLinearVelocity(v(-15,0));registerObject({body:body,type:'rect',hw:3,hh:1,color:'#2c3e50'});var tail=w.createBody({type:'dynamic',position:v(x+5,y)});tail.createFixture(p.Box(2.5,0.3),{density:0.3});registerObject({body:tail,type:'rect',hw:2.5,hh:0.3,color:'#34495e'});w.createJoint(new p.WeldJoint({},body,tail,v(x+3,y)));var rotor=w.createBody({type:'dynamic',position:v(x,y-2.5)});rotor.createFixture(p.Box(5,0.15),{density:0.1,isSensor:true});registerObject({body:rotor,type:'rect',hw:5,hh:0.15,color:'#7f8c8d'});var rj=w.createJoint(new p.RevoluteJoint({enableMotor:true,motorSpeed:50,maxMotorTorque:100},body,rotor,v(x,y-2)));var tailRotor=w.createBody({type:'dynamic',position:v(x+7.5,y)});tailRotor.createFixture(p.Box(0.1,1),{density:0.05,isSensor:true});registerObject({body:tailRotor,type:'rect',hw:0.1,hh:1,color:'#95a5a6'});w.createJoint(new p.RevoluteJoint({enableMotor:true,motorSpeed:80,maxMotorTorque:50},tail,tailRotor,v(x+7.5,y)));var t=0,hover=y;return{update:function(){t++;var pos=body.getPosition(),tg=getTarget();var lift=1200;if(pos.y>hover)lift=1600;if(pos.y<hover-3)lift=800;body.applyForce(v(0,-lift),pos);if(tg){var dx=tg.x-pos.x;if(Math.abs(dx)>5)body.applyForce(v(dx>0?80:-80,0),pos)}var ang=body.getAngle();if(Math.abs(ang)>0.1)body.applyTorque(-ang*200);if(tg&&t%120==0){var dx=tg.x-pos.x,dy=tg.y-pos.y,dist=Math.sqrt(dx*dx+dy*dy),nx=dx/dist,ny=dy/dist;var bul=w.createBody({type:'dynamic',position:v(pos.x,pos.y+2)});bul.createFixture(p.Circle(0.4),{density:5});bul.setLinearVelocity(v(nx*70,ny*70));registerObject({body:bul,type:'circle',radius:0.4,color:'#e74c3c'})}}}`,

  'rain': `var m,v=planck.Vec2(-5,0),t=0;[0,-3.5,3.5].forEach(function(i){var b=world.createBody({type:'kinematic',position:planck.Vec2(spawnX+i,spawnY+(i?1:0)),linearVelocity:v});b.createFixture(planck.Circle(i?2.5:3.2));registerObject({body:b,type:'circle',radius:i?2.5:3.2,color:'#bdc3c7'});if(!i)m=b;});return{update:function(){if(++t%3==0){var r=world.createBody({type:'dynamic',position:planck.Vec2(m.getPosition().x+(Math.random()*14-7),m.getPosition().y+3)});r.createFixture(planck.Circle(.25),{density:.5});r.setLinearVelocity(planck.Vec2(-5,25));registerObject({body:r,type:'circle',radius:.25,color:'#3498db'})}}}`,

  'train': `var c=spawnX,d=spawnY,v=planck.Vec2,w=world,b=w.createBody({type:'dynamic',position:v(c,d)});b.createFixture(planck.Box(5,1.5),{density:5,friction:.3});registerObject({body:b,type:'rect',hw:5,hh:1.5,color:'#c0392b'});var k=w.createBody({type:'dynamic',position:v(c+3,d-2)});k.createFixture(planck.Box(1.5,1.5),{density:2});registerObject({body:k,type:'rect',hw:1.5,hh:1.5,color:'#922b21'});w.createJoint(new planck.WeldJoint({},b,k,v(c+3,d-0.5)));var s=w.createBody({type:'dynamic',position:v(c-3,d-2.5)});s.createFixture(planck.Box(0.6,1),{density:1});registerObject({body:s,type:'rect',hw:0.6,hh:1,color:'#2c3e50'});w.createJoint(new planck.WeldJoint({},b,s,v(c-3,d-1.5)));var g=w.createBody({type:'dynamic',position:v(c-5.2,d+1),angle:-0.6});g.createFixture(planck.Box(0.2,1.6),{density:2});registerObject({body:g,type:'rect',hw:0.2,hh:1.6,color:'#7f8c8d'});w.createJoint(new planck.WeldJoint({},b,g,v(c-5,d+1)));var js={enableMotor:true,motorSpeed:-15,maxMotorTorque:5000};[-4,0,4].forEach(function(i){var wh=w.createBody({type:'dynamic',position:v(c+i,d+3)});wh.createFixture(planck.Circle(1.2),{density:3,friction:2});registerObject({body:wh,type:'circle',radius:1.2,color:'#34495e'});w.createJoint(new planck.RevoluteJoint(js,b,wh,wh.getPosition()))});var t=0;return{update:function(){if(++t%6==0){var p=s.getPosition(),sm=w.createBody({type:'dynamic',position:v(p.x+(Math.random()*1-0.5),p.y-1.2),gravityScale:-0.3});sm.createFixture(planck.Circle(0.3+Math.random()*0.3),{density:.01,isSensor:true});sm.setLinearVelocity(v(-5-Math.random()*3,-8-Math.random()*5));sm.setAngularVelocity(Math.random()*2-1);registerObject({body:sm,type:'circle',radius:0.4,color:'#ddd'})}}}`,

  'tank': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world,G=40,SPD=80,body=w.createBody({type:'dynamic',position:v(x,y)});body.createFixture(p.Box(5,1.5),{density:3,friction:.5});registerObject({body:body,type:'rect',hw:5,hh:1.5,color:'#4a5d23'});var wOpts={enableMotor:true,motorSpeed:-8,maxMotorTorque:3000};[-3.5,0,3.5].forEach(function(ox){var wh=w.createBody({type:'dynamic',position:v(x+ox,y+2.2)});wh.createFixture(p.Circle(1.3),{density:2,friction:1.5});registerObject({body:wh,type:'circle',radius:1.3,color:'#2d2d2d'});w.createJoint(new p.RevoluteJoint(wOpts,body,wh,wh.getPosition()))});var tb=w.createBody({type:'dynamic',position:v(x-1,y-2.2)});tb.createFixture(p.Box(2,.8),{density:1});registerObject({body:tb,type:'rect',hw:2,hh:.8,color:'#3d4a1f'});w.createJoint(new p.WeldJoint({},body,tb,v(x-1,y-1.5)));var br=w.createBody({type:'dynamic',position:v(x+1.5,y-2.2)});br.createFixture(p.Box(3,.35),{density:.5});registerObject({body:br,type:'rect',hw:3,hh:.35,color:'#2a3515'});var tj=w.createJoint(new p.RevoluteJoint({enableMotor:true,maxMotorTorque:800,motorSpeed:0},tb,br,v(x-1,y-2.2)));var t=0;return{update:function(){t++;var tg=getTarget();if(tg){var bp=br.getPosition(),dx=tg.x-bp.x,dy=tg.y-bp.y,dist=Math.sqrt(dx*dx+dy*dy),ft=dist/SPD,drop=0.5*G*ft*ft,aimY=tg.y-drop,ang=Math.atan2(aimY-bp.y,dx),cur=br.getAngle(),diff=ang-cur;while(diff>Math.PI)diff-=2*Math.PI;while(diff<-Math.PI)diff+=2*Math.PI;tj.setMotorSpeed(diff*5)}if(t%90==0){var bp=br.getPosition(),ba=br.getAngle(),bx=bp.x+Math.cos(ba)*4,by=bp.y+Math.sin(ba)*4,bl=w.createBody({type:'dynamic',position:v(bx,by)});bl.createFixture(p.Circle(.5),{density:8,restitution:.2});bl.setLinearVelocity(v(Math.cos(ba)*SPD,Math.sin(ba)*SPD));registerObject({body:bl,type:'circle',radius:.5,color:'#e74c3c'})}}}`,

  'ball': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world;var b=w.createBody({type:'dynamic',position:v(x,y)});b.createFixture(p.Circle(2.5),{density:2,restitution:0.95,friction:0.1});registerObject({body:b,type:'circle',radius:2.5,color:'#e74c3c'});return{update:function(){var tg=getTarget();if(tg){var pos=b.getPosition(),dx=tg.x-pos.x,dy=tg.y-pos.y,dist=Math.sqrt(dx*dx+dy*dy);if(dist>2){b.applyForce(v(dx/dist*80,dy/dist*80),pos)}}}}`,

  'car': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world;var body=w.createBody({type:'dynamic',position:v(x,y)});body.createFixture(p.Box(4,1),{density:2,friction:0.3});registerObject({body:body,type:'rect',hw:4,hh:1,color:'#3498db'});var wOpts={enableMotor:true,motorSpeed:-20,maxMotorTorque:2000};[-2.5,2.5].forEach(function(ox){var wh=w.createBody({type:'dynamic',position:v(x+ox,y+1.5)});wh.createFixture(p.Circle(1),{density:1.5,friction:2});registerObject({body:wh,type:'circle',radius:1,color:'#2c3e50'});w.createJoint(new p.RevoluteJoint(wOpts,body,wh,wh.getPosition()))})`,

  'cannon': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world,G=40,SPD=90;var base=w.createBody({type:'dynamic',position:v(x,y)});base.createFixture(p.Box(3,1.5),{density:10,friction:0.8});registerObject({body:base,type:'rect',hw:3,hh:1.5,color:'#5d4037'});var barrel=w.createBody({type:'dynamic',position:v(x-2,y-1)});barrel.createFixture(p.Box(4,0.6),{density:3});registerObject({body:barrel,type:'rect',hw:4,hh:0.6,color:'#424242'});var bj=w.createJoint(new p.RevoluteJoint({enableMotor:true,maxMotorTorque:5000,motorSpeed:0,enableLimit:true,lowerAngle:-1,upperAngle:0.3},base,barrel,v(x,y-1)));var t=0;return{update:function(){t++;var tg=getTarget();if(tg){var bp=barrel.getPosition(),dx=tg.x-bp.x,dy=tg.y-bp.y,dist=Math.sqrt(dx*dx+dy*dy),ft=dist/SPD,drop=0.5*G*ft*ft,ang=Math.atan2(tg.y-drop-bp.y,dx),cur=barrel.getAngle(),diff=ang-cur;while(diff>Math.PI)diff-=2*Math.PI;while(diff<-Math.PI)diff+=2*Math.PI;bj.setMotorSpeed(diff*3)}if(t%70==0){var ba=barrel.getAngle(),tip=barrel.getWorldPoint(v(-4,0)),bl=w.createBody({type:'dynamic',position:tip});bl.createFixture(p.Circle(0.8),{density:12,restitution:0.1});bl.setLinearVelocity(v(Math.cos(ba)*SPD,Math.sin(ba)*SPD));registerObject({body:bl,type:'circle',radius:0.8,color:'#1a1a1a'})}}}`,

  'rocket': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world;var body=w.createBody({type:'dynamic',position:v(x,y),angularDamping:3,gravityScale:0.15});body.createFixture(p.Box(3,0.8),{density:2});body.createFixture(p.Polygon([v(-3,0),v(-4,-1),v(-4,1)]),{density:0.5});registerObject({body:body,type:'rect',hw:3,hh:0.8,color:'#c0392b'});var t=0,exploded=false;return{update:function(){t++;var pos=body.getPosition(),tg=getTarget();if(!exploded&&tg){var dx=tg.x-pos.x,dy=tg.y-pos.y,dist=Math.sqrt(dx*dx+dy*dy),ang=Math.atan2(dy,dx),cur=body.getAngle(),diff=ang-cur;while(diff>Math.PI)diff-=2*Math.PI;while(diff<-Math.PI)diff+=2*Math.PI;body.setAngularVelocity(diff*5);body.applyForce(v(Math.cos(cur)*300,Math.sin(cur)*300),pos);if(dist<5&&!exploded){exploded=true;for(var i=0;i<12;i++){var a=i*Math.PI*2/12,spd=35+Math.random()*20,fr=w.createBody({type:'dynamic',position:v(pos.x+Math.cos(a)*2,pos.y+Math.sin(a)*2)});fr.createFixture(p.Circle(0.7),{density:6});fr.setLinearVelocity(v(Math.cos(a)*spd,Math.sin(a)*spd));registerObject({body:fr,type:'circle',radius:0.7,color:'#e74c3c'})}w.destroyBody(body)}}if(!exploded&&t%3==0){var ba=body.getAngle(),ex=pos.x-Math.cos(ba)*3.5,ey=pos.y-Math.sin(ba)*3.5,fl=w.createBody({type:'dynamic',position:v(ex,ey),gravityScale:-0.5});fl.createFixture(p.Circle(0.3+Math.random()*0.3),{density:0.01,isSensor:true});fl.setLinearVelocity(v(-Math.cos(ba)*20+Math.random()*10-5,-Math.sin(ba)*20+Math.random()*10-5));registerObject({body:fl,type:'circle',radius:0.4,color:Math.random()>0.5?'#e67e22':'#f1c40f'})}}}`,

  'bomb': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world;var body=w.createBody({type:'dynamic',position:v(x,y)});body.createFixture(p.Circle(2),{density:8,restitution:0.1});registerObject({body:body,type:'circle',radius:2,color:'#2c3e50'});var fuse=w.createBody({type:'dynamic',position:v(x,y-2.5)});fuse.createFixture(p.Box(0.2,0.8),{density:0.1});registerObject({body:fuse,type:'rect',hw:0.2,hh:0.8,color:'#e67e22'});w.createJoint(new p.WeldJoint({},body,fuse,v(x,y-2)));body.setLinearVelocity(v(-35,-15));var t=0,exploded=false;return{update:function(){t++;if(!exploded&&t>90){exploded=true;var pos=body.getPosition();for(var i=0;i<12;i++){var ang=i*Math.PI*2/12,spd=30+Math.random()*20,frag=w.createBody({type:'dynamic',position:v(pos.x+Math.cos(ang)*2.5,pos.y+Math.sin(ang)*2.5)});frag.createFixture(p.Circle(0.6),{density:5,restitution:0.3});frag.setLinearVelocity(v(Math.cos(ang)*spd,Math.sin(ang)*spd));registerObject({body:frag,type:'circle',radius:0.6,color:'#e74c3c'})}w.destroyBody(body);w.destroyBody(fuse)}}}`,

  'boulder': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world;var b=w.createBody({type:'dynamic',position:v(x,y)});b.createFixture(p.Circle(4),{density:15,friction:0.6,restitution:0.2});b.setLinearVelocity(v(-25,0));b.setAngularVelocity(-3);registerObject({body:b,type:'circle',radius:4,color:'#7f8c8d'})`,

  'missile': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world;var body=w.createBody({type:'dynamic',position:v(x,y),angularDamping:2,bullet:true,gravityScale:0.1});body.createFixture(p.Box(2,0.5),{density:1.5});body.createFixture(p.Polygon([v(2,0),v(1.5,-0.5),v(1.5,0.5)]),{density:0.3});registerObject({body:body,type:'rect',hw:2,hh:0.5,color:'#34495e'});var t=0,exploded=false;return{update:function(){t++;var pos=body.getPosition(),tg=getTarget();if(!exploded&&tg){var dx=tg.x-pos.x,dy=tg.y-pos.y,dist=Math.sqrt(dx*dx+dy*dy),ang=Math.atan2(dy,dx),cur=body.getAngle(),diff=ang-cur;while(diff>Math.PI)diff-=2*Math.PI;while(diff<-Math.PI)diff+=2*Math.PI;body.setAngularVelocity(diff*6);body.applyForce(v(Math.cos(cur)*200,Math.sin(cur)*200),pos);if(dist<4&&!exploded){exploded=true;for(var i=0;i<10;i++){var a=i*Math.PI*2/10,spd=30+Math.random()*20,fr=w.createBody({type:'dynamic',position:v(pos.x+Math.cos(a)*1.5,pos.y+Math.sin(a)*1.5)});fr.createFixture(p.Circle(0.5),{density:5});fr.setLinearVelocity(v(Math.cos(a)*spd,Math.sin(a)*spd));registerObject({body:fr,type:'circle',radius:0.5,color:'#f39c12'})}w.destroyBody(body)}}if(!exploded&&t%2==0){var ba=body.getAngle(),ex=pos.x-Math.cos(ba)*2.5,ey=pos.y-Math.sin(ba)*2.5,fl=w.createBody({type:'dynamic',position:v(ex,ey),gravityScale:0});fl.createFixture(p.Circle(0.2),{density:0.01,isSensor:true});fl.setLinearVelocity(v(-Math.cos(ba)*15,-Math.sin(ba)*15));registerObject({body:fl,type:'circle',radius:0.2,color:'#e74c3c'})}}}`,

  'turret': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world,G=40,SPD=110;var base=w.createBody({type:'dynamic',position:v(x,y)});base.createFixture(p.Box(2.5,2.5),{density:20,friction:1});registerObject({body:base,type:'rect',hw:2.5,hh:2.5,color:'#7f8c8d'});var gun=w.createBody({type:'dynamic',position:v(x-2,y)});gun.createFixture(p.Box(4,0.5),{density:2});registerObject({body:gun,type:'rect',hw:4,hh:0.5,color:'#2c3e50'});var gj=w.createJoint(new p.RevoluteJoint({enableMotor:true,maxMotorTorque:4000,motorSpeed:0},base,gun,v(x,y)));var t=0;return{update:function(){t++;var tg=getTarget();if(tg){var gp=gun.getPosition(),dx=tg.x-gp.x,dy=tg.y-gp.y,dist=Math.sqrt(dx*dx+dy*dy),ft=dist/SPD,drop=0.5*G*ft*ft,ang=Math.atan2(tg.y-drop-gp.y,dx),cur=gun.getAngle(),diff=ang-cur;while(diff>Math.PI)diff-=2*Math.PI;while(diff<-Math.PI)diff+=2*Math.PI;gj.setMotorSpeed(diff*10)}if(t%10==0){var ga=gun.getAngle(),tip=gun.getWorldPoint(v(-4,0)),bl=w.createBody({type:'dynamic',position:tip});bl.createFixture(p.Circle(0.6),{density:8,restitution:0.2});bl.setLinearVelocity(v(Math.cos(ga)*SPD,Math.sin(ga)*SPD));registerObject({body:bl,type:'circle',radius:0.6,color:'#f39c12'})}}}`,

  'wrecking ball': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world;var anchor=w.createBody({type:'static',position:v(x,y-15)});var ball=w.createBody({type:'dynamic',position:v(x+20,y)});ball.createFixture(p.Circle(4),{density:20,restitution:0.3,friction:0.5});registerObject({body:ball,type:'circle',radius:4,color:'#2c3e50'});var prev=anchor,len=3;for(var i=0;i<8;i++){var link=w.createBody({type:'dynamic',position:v(x+(i+1)*2.5,y-15+i*2)});link.createFixture(p.Box(1.2,0.4),{density:2});registerObject({body:link,type:'rect',hw:1.2,hh:0.4,color:'#7f8c8d'});w.createJoint(new p.RevoluteJoint({},prev,link,prev.getPosition()));prev=link}w.createJoint(new p.RevoluteJoint({},prev,ball,prev.getPosition()));ball.setLinearVelocity(v(-30,0))`,

  'meteor': `var p=planck,v=p.Vec2,x=spawnX,y=spawnY,w=world;var tg=getTarget(),dx=0,dy=1;if(tg){dx=tg.x-x;dy=tg.y-y;var d=Math.sqrt(dx*dx+dy*dy);dx/=d;dy/=d}var body=w.createBody({type:'dynamic',position:v(x,y)});body.createFixture(p.Circle(3),{density:12,restitution:0.2});body.setLinearVelocity(v(dx*50,dy*50));body.setAngularVelocity(2);registerObject({body:body,type:'circle',radius:3,color:'#c0392b'});var t=0;return{update:function(){t++;if(t%2==0){var pos=body.getPosition(),vel=body.getLinearVelocity(),fl=w.createBody({type:'dynamic',position:v(pos.x-vel.x*0.02+Math.random()*2-1,pos.y-vel.y*0.02+Math.random()*2-1),gravityScale:0});fl.createFixture(p.Circle(0.4+Math.random()*0.5),{density:0.01,isSensor:true});fl.setLinearVelocity(v(-vel.x*0.3,-vel.y*0.3));registerObject({body:fl,type:'circle',radius:0.5,color:Math.random()>0.5?'#e67e22':'#f39c12'})}}}`,
};
